// food-recipes.search.http
### case: limit page sort
GET http://localhost:3000/api/v1/movie-reviews?limit&page=2&sortBy=id
Content-Type: application/json


# ### case: search
GET http://localhost:3000/api/v1/movie-reviews?limit=3&page=1&sortBy=name&search=l
Content-Type: application/json


# ### case: get
GET http://localhost:3000/api/v1/movie-reviews/6
Content-Type: application/json